name: build-and-push-docker-image

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  build:
    if: >
      github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == 'staging'
    runs-on: [self-hosted, builder]
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t a12zc/helloworld:latest .
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push a12zc/helloworld:latest
      - run: |
          docker compose pull
          docker compose up -d
          docker compose restart
