name: staging try 

on: 
  pull_request:
    branches: [main]
    types: [closed]
    
    #pull requests:
    
jobs:
  build: 
    if: github.event.pull_request.merged == true
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t ***/helloworld:tagname .
      - run: docker login -u${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - run: docker push a12zc/helloworld:tagname
        
